### ISSUE TITLE
impossible import 

### ISSUE THREAD

**Issue by zakarialaoui10** [withastro/docs#9476] opened 2024-09-24 19:20 UTC
### 📚 Subject area/topic

Client-side interactivity 

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/client-side-scripts/

### 📋 Description of content that is out-of-date or incorrect

I have found this on the docs : 
```html
<button data-confetti-button>Celebrate!</button>

<script>
  // Import npm modules.
  import confetti from 'canvas-confetti';

  // Find our component DOM on the page.
  const buttons = document.querySelectorAll('[data-confetti-button]');

  // Add event listeners to fire confetti when a button is clicked.
  buttons.forEach((button) => {
    button.addEventListener('click', () => confetti());
  });
</script>
```

In fact you can't import node_modules from script tag in astro component .
You have to use CDN instead

**Comment by sarah11918** [comment] 2024-09-24 20:01
Hi! As documented here, you can import node modules: https://docs.astro.build/en/guides/client-side-scripts/#script-processing in script tags!

If you're having trouble getting this to work then this may be the specific import you're trying to use, a problem in your project or a bug in Astro, but this is intended behavior. So, I will close this as a docs issue but if you would like help troubleshooting a script that is not working as expected, you can join our Discord and people will be able to look over code with you and would be happy to try and help! https://astro.build/chat

**Closed by sarah11918** 2024-09-24 20:01 UTC
Labels: improve documentation

**Comment by zakarialaoui10** [comment] 2024-09-28 11:33
@sarah11918 
I tested the example provided in the documentation, but it didn't work as expected.
