### ISSUE TITLE
Searching for error reference pages shows description with the title

### ISSUE THREAD

**Issue by VoxelMC** [withastro/docs#6426] opened 2024-01-16 16:15 UTC
### 📝 Issue Description

When searching for error reference pages, the chip title (?) is concatenated to the error's description.

### 📋 On which page(s) it occurs

All pages, search bar.

### 🤔 Expected Behavior

The description is usually below the item, as such:
<img width="540" alt="image" src="https://github.com/withastro/docs/assets/20650404/9b4e4a1a-2158-4a90-a079-80d1182a21c3">

### 👀 Current Behavior

<img width="537" alt="image" src="https://github.com/withastro/docs/assets/20650404/7d1804f9-9609-4265-9072-1f23fda5453e">
<img width="544" alt="image" src="https://github.com/withastro/docs/assets/20650404/6ad8532d-651a-4cc8-9632-d20488ddccf1">

##### Also present in translations (just to be sure)

<img width="537" alt="image" src="https://github.com/withastro/docs/assets/20650404/bc8810c9-2647-47ba-ab37-8eb6c9d33613">

### 🖥️ Browser

Arc, Chrome, Safari

### 📄 Additional Information

If possible, I would like to solve the problem!

**Comment by Fryuni** [comment] 2024-01-30 03:09
First, there is a mixup here. There are three types of search results:
![image](https://github.com/withastro/docs/assets/11063910/607acd7a-0200-42ff-95fd-12e98f9d7b84)

- The first one is a page result based on the title and head metadata of the page. It shows the name of the page only.
- The second is a heading match, which is based on the name of the section. It shows the content of the heading on top and the name of the page on the bottom.
- The third one is a content match, which is based on the actual content of a paragraph. It shows the matched snippet of the paragraph above and the name of the page below.

What you sent as "expected behavior" is an example of the second case, while the "current behavior" is the third case. That by itself is not a bug.

---

Now on to why this happens for errors and what we need to change to solve it. It is actually two causes for similar effects.

#### Cause one

The search indexes are generated from the final generated HTML for the pages. The error reference list is generated with a single paragraph containing a line break (`<br>`), that line break is ignored for the search index so the name and description are concatenated in the snippet. There is no heading for it, the closest heading is just "Astro Errors", so the match is in the content, the third case from above.
![image](https://github.com/withastro/docs/assets/11063910/55f52125-f221-4c8d-a033-f277d7595dde)

Additionally, when you search for an error you get _first_ a link to the list of errors (which contains the text for every error) and second a link to the actual reference for the error you are searching for.
![image](https://github.com/withastro/docs/assets/11063910/824c7ff8-905f-4953-9fbb-12845171654f)

I think the section that lists the errors should be excluded from the search. Just the list section, not the entire page. This way when someone searches for an error they would be directed directly to the reference of the error they are looking for instead of the top of the error list page.

I don't know if there is some way to have Algolia consider those lists as lower priority so it is included but shows up below the specific reference page.

WDYT about this idea @sarah11918?

#### Cause two

Even if you get the result pointing to the actual reference page for the error. The _title_ of that page is a description of the error, not the name.
![image](https://github.com/withastro/docs/assets/11063910/e9a6a409-35b9-43af-a0e7-067bdee2d12d)

This would need to be changed in the error reference generator to make the title be the name of the error and the description be part of the content. I'm not sure whether this would be worth the effort, I edited it locally to see how it looks like and I personally don't see much value to justify the change. But I'm not against it if someone (maybe you) wants to contribute that.

**Comment by VoxelMC** [comment] 2024-02-01 20:07
> First, there is a mixup here. There are three types of search results: ![image](https://private-user-images.githubusercontent.com/11063910/300664325-607acd7a-0200-42ff-95fd-12e98f9d7b84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTgyMjUsIm5iZiI6MTcwNjgxNzkyNSwicGF0aCI6Ii8xMTA2MzkxMC8zMDA2NjQzMjUtNjA3YWNkN2EtMDIwMC00MmZmLTk1ZmQtMTJlOThmOWQ3Yjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIwMDUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYjdjYWUxY2M3NDYyYmNjZWFlMTdiNGQ3NTdjNjk2NGZlNjg3YWRmYjVhMWFiNGUzMjgyNzdhNDk3Y2MyMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u5x-xf8ylGbUgio_bW9IXa6urJmxKAU8Wmjjd6RdTPU)
> 
> * The first one is a page result based on the title and head metadata of the page. It shows the name of the page only.
> * The second is a heading match, which is based on the name of the section. It shows the content of the heading on top and the name of the page on the bottom.
> * The third one is a content match, which is based on the actual content of a paragraph. It shows the matched snippet of the paragraph above and the name of the page below.
> 
> What you sent as "expected behavior" is an example of the second case, while the "current behavior" is the third case. That by itself is not a bug.
> 
> Now on to why this happens for errors and what we need to change to solve it. It is actually two causes for similar effects.
> 
> #### Cause one
> The search indexes are generated from the final generated HTML for the pages. The error reference list is generated with a single paragraph containing a line break (`<br>`), that line break is ignored for the search index so the name and description are concatenated in the snippet. There is no heading for it, the closest heading is just "Astro Errors", so the match is in the content, the third case from above. ![image](https://private-user-images.githubusercontent.com/11063910/300663027-55f52125-f221-4c8d-a033-f277d7595dde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTgyMjUsIm5iZiI6MTcwNjgxNzkyNSwicGF0aCI6Ii8xMTA2MzkxMC8zMDA2NjMwMjctNTVmNTIxMjUtZjIyMS00YzhkLWEwMzMtZjI3N2Q3NTk1ZGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIwMDUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNDgwNjJkNDJlY2JmOWFkMTZhMTA5NGE0YzU2MWI0ZDhkYWU2NDg3OWU0MDk5ZmZmYjlhYTA1ZDUwOTA3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V9pFMKhA89OGmQwrqYRpHFfln3b35pGAwl9sZpewWcQ)
> 
> Additionally, when you search for an error you get _first_ a link to the list of errors (which contains the text for every error) and second a link to the actual reference for the error you are searching for. ![image](https://private-user-images.githubusercontent.com/11063910/300663448-824c7ff8-905f-4953-9fbb-12845171654f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTgyMjUsIm5iZiI6MTcwNjgxNzkyNSwicGF0aCI6Ii8xMTA2MzkxMC8zMDA2NjM0NDgtODI0YzdmZjgtOTA1Zi00OTUzLTlmYmItMTI4NDUxNzE2NTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIwMDUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYjY3ODJiOTM2NjZlNjJjZmNiY2E1ODYwMDI3OGMwMDhkOTJhNTAzMmZjMWFhNGRlY2IxNTFlNzg0N2M2ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dev8qwR0Ei5nvuzOH6Y5wE9dV4UzVcqY-FDYB-q-CyA)
> 
> I think the section that lists the errors should be excluded from the search. Just the list section, not the entire page. This way when someone searches for an error they would be directed directly to the reference of the error they are looking for instead of the top of the error list page.
> 
> I don't know if there is some way to have Algolia consider those lists as lower priority so it is included but shows up below the specific reference page.
> 
> WDYT about this idea @sarah11918?
> 
> #### Cause two
> Even if you get the result pointing to the actual reference page for the error. The _title_ of that page is a description of the error, not the name. ![image](https://private-user-images.githubusercontent.com/11063910/300666094-e9a6a409-35b9-43af-a0e7-067bdee2d12d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTgyMjUsIm5iZiI6MTcwNjgxNzkyNSwicGF0aCI6Ii8xMTA2MzkxMC8zMDA2NjYwOTQtZTlhNmE0MDktMzViOS00M2FmLWEwZTctMDY3YmRlZTJkMTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIwMDUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMjdjYTVhMWIxMzYwYjU2YTI1YTg2ZDlkNDg1Y2MzYTEwNmViMzkyZTQwY2FiZGUwNjhkN2JhMTFlMTcyOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NWy-jXxf2OA_8bi2aDHng6hXyyw6ZlBpgqLLyvpxjtM)
> 
> This would need to be changed in the error reference generator to make the title be the name of the error and the description be part of the content. I'm not sure whether this would be worth the effort, I edited it locally to see how it looks like and I personally don't see much value to justify the change. But I'm not against it if someone (maybe you) wants to contribute that.

I believe it will help to fix, I love our clean docs! Anything to round stuff out like this :P

If it is decided to move forward, I can contribute it!

**Comment by VoxelMC** [comment] 2024-03-05 07:08
> Just catching up here:
> 
> > I think the section that lists the errors should be excluded from the search. Just the list section, not the entire page. This way when someone searches for an error they would be directed directly to the reference of the error they are looking for instead of the top of the error list page.
> > I don't know if there is some way to have Algolia consider those lists as lower priority so it is included but shows up below the specific reference page.
> 
> So, my proposal might be, can we exclude that one single error reference page from showing up in search AT ALL? There is no item there that doesn't already have its own page. What if hits only went directly to the error message's own page?
> 
> > Even if you get the result pointing to the actual reference page for the error. The title of that page is a description of the error, not the name.
> 
> Agreed I care less about this. It's an entire page devoted to the error message, and you're gonna get there. I think that's fine? 😄
> 
> So, perhaps the only fix needed is to exclude the one main error reference page from Algolia search results. Tell me what I'm missing?

Yup! I agree. If it ain't broke...
I would agree that getting rid of that error reference page from Algolia is quite prudent. I always find myself there and its a pain to navigate! How would we even do this? Manually in Algolia?

**Comment by Fryuni** [comment] 2024-03-10 04:09
Sorry for the delayed reply.

> > Even if you get the result pointing to the actual reference page for the error. The title of that page is a description of the error, not the name.
> 
> Agreed I care less about this. It's an entire page devoted to the error message, and you're gonna get there. I think that's fine? 😄
> 
> So, perhaps the only fix needed is to exclude the one main error reference page from Algolia search results. Tell me what I'm missing?

I think most people will search for the name/code of the error since that is an exact identifier of the problem they are facing, and that search doesn't work well because the code is in the middle of the text.

I'm proposing to have the _name_ of the error, which is the same as its constant name and the code that shows in red before the error message, in the title for better indexing.

Currently, we have this:
![image](https://github.com/withastro/docs/assets/11063910/4f81ad49-cf9f-4eb4-b2b1-2bfe97aeee79)
The error code is in the middle of the text, which is matched with a lower priority by Algolia.

If the user finds an error during a build instead of during dev, the title is not even present anywhere in the error message:
![image](https://github.com/withastro/docs/assets/11063910/fcde066a-2e05-417c-9c40-88a6ab60029a)

Yes, the error message includes a link directly to the correct error page, but we know people start asking questions before they get to that line, especially if the error happens on CI without the colors.

My proposal is to change to this (or something similar):
![image](https://github.com/withastro/docs/assets/11063910/3556af22-1479-4bf0-90ee-b4e88e24d97c)

The error code, highlighted prominently in red on the error message, is now the page title. The `title` property of the error data is now in both the content and the `description` field in the front matter (previously empty).

**Comment by sarah11918** [comment] 2024-03-18 19:34
Gotta love doc'ing for Algolia, eh?

That's an excellent solution, Fryuni! So I think two things that would BOTH help (and are separate) are:
- we exclude the main error page from Algolia results
- We could update the format of the errors written in JSDOC in the astro repo (or adjust the ci command that pulls them in and processes them? I would have to look to see which of these two things is responsible for the exact formatting, since I don't remember off the top of my head.)

I'll ask @Princesseuh to weigh in here for thoughts: basically, it does make sense that the error message itself is the thing people will type into Algolia, so it probably makes sense to optimize formatting for headings etc. that will get picked up better.

**Comment by Princesseuh** [comment] 2024-03-18 20:11
The formatting is done exclusively in docs, happy to adapt it to whatever is best for search!

My only thought is that it might not be true that people search for the codes - I wouldn't actually be surprised if people never do.

**Comment by sarah11918** [comment] 2024-03-18 20:17
OK, then I'm happy to let people have a discussion here about what they think makes the most sense for "trapping" the errors in an Algolia search! I'm adding `help wanted` to this so we can discuss!

**Comment by sarah11918** [comment] 2024-06-19 15:52
So, I don't know whether anything changed, but I just searched for `LocalImageUsedWrongly` and I got both the main error page, and the specific error reference page, both look helpful to me.

![image](https://github.com/withastro/docs/assets/5098874/524282a2-a51b-4f02-9669-3fd1eea0f5ed)

I think the searching here is fine, but what's less ideal is that if you click on the link to the main error page, you're not taken directly to the specific error because they are not anchors themselves I guess? Only at the top of the page, then you have to search for the error.

But, I believe either way you're gonna find it! The improvement I *could* see is that on the main error page, maybe instead of a bulleted list these are all e.g. `<h4>`s? (or specifically `<h3>`s that are HTML, not Markdown, so they don't show up in the TOC/on this page).

So, I'll close this as not an "issue to fix" per se, but I don't mind if anyone on their own wants to experiment!

**Closed by sarah11918** 2024-06-19 15:52 UTC
Labels: site improvement, help wanted, help - leave feedback
