### ISSUE TITLE
⚠️ Issue. The Astro redirect does not work?

### ISSUE THREAD

**Issue by marcitqualab** [withastro/docs#9493] opened 2024-09-26 07:48 UTC
I have setup a working example of this recipe here. 
https://github.com/marcitqualab/astro-forms/blob/main/htmlForm/src/components/ApiForm.astro

The project is open and ready to test by anyone, it uses dev container to facilitate the dev env setup.
https://github.com/marcitqualab/astro-forms

When I run this example and the form does not have errors then the code attempts to do run the line 
```
return Astro.redirect("/login");
```
This redirect does not work and this error message appears in the terminal.
```
The response has already been sent to the browser and cannot be altered.
```

Has something changed in Astro?

**Comment by ArmandPhilippot** [comment] 2024-09-26 10:12
Hi @marcitqualab,

By "this recipe", I guess you are referring to [Build HTML forms in Astro pages](https://docs.astro.build/en/recipes/build-forms/).

Your reproduction has a slight difference which is causing the problem: the recipe handle the form validation in **an Astro page** and not in a component! If you move, all the code from `components/ApiForm.astro` to `pages/index.astro`, you'll see the redirection now works.

I don't know where this limitation comes from, but it seems to be the expected behavior. There is [a reference for this error](https://docs.astro.build/en/reference/errors/response-sent-error/) indicating where the problem comes from:

> **Making changes to the response**, such as setting headers, cookies, and the status code **cannot be done outside of page components**.

And a redirect is a change in the response... 😉

**Comment by marcitqualab** [comment] 2024-09-27 02:18
Hello Armand, 

Yes, the error description did not help much and it is a bit confusing.
You are correct, that was the problem. I have refactored the ApiForm into the index page and it works.

However, I might be missing something here. 
I am not really sure what is the point if I can not create form components. This means that I need to duplicate the form code to any page where I want the same form? Let's say it is a Call to Action form. 
Also I will have to make every page with a form a dynamic page, when I only need the component to be dynamic.
I was expecting to be able to inject the same form component into any page.
Maybe for that I need to implement a component with a framework like React or Vue?

**Comment by ArmandPhilippot** [comment] 2024-09-27 10:29
I think this recipe is designed for one time use like a contact form only accessible in a contact page.
In your case, you might be interested in the other recipe: [Build forms with API routes](https://docs.astro.build/en/recipes/build-forms-api/) which indeed involves UI Framework like React or Vue.

But if you don't want to use React/Vue just for that, you can also build a reusable component for your form using an API route and an Astro component.
In the component, you will need a [client-side script](https://docs.astro.build/en/guides/client-side-scripts/#handle-onclick-and-other-events) to listen for the submit event and forward the data to your API route. You can also [use a web component](https://docs.astro.build/en/guides/client-side-scripts/#web-components-with-custom-elements) for that which can be more convenient if you want to display errors coming from the API route.
If you need a redirection, you can also handle that [in your API route](https://docs.astro.build/en/guides/endpoints/#redirects)!

**Comment by marcitqualab** [comment] 2024-09-27 22:12
Perfect many thanks, I'll check it out :-)

**Comment by sarah11918** [comment] 2024-10-03 11:03
Closing this as the immediate problem is resolved, and at this moment there doesn't appear to be anything actionable for docs! 🙌

**Closed by sarah11918** 2024-10-03 11:03 UTC
