### ISSUE TITLE
Docs suggest `Astro.props.frontmatter || Astro.props`, but doesn't work for much more than a title

### ISSUE THREAD

**Issue by adiabatic** [withastro/docs#2811] opened 2023-03-09 05:00 UTC
This might not be a docs issue, but the docs suggest using a really good idea that falls flat given my slightly-more-complicated use case.

[Using one Layout for `.md`, `.mdx`, and `.astro`](https://docs.astro.build/en/core-concepts/layouts/#using-one-layout-for-md-mdx-and-astro) suggests pulling a `title` out of either the `frontmatter` or `props`:

```typescript
const { title } = Astro.props.frontmatter || Astro.props;
```

This sounds great, as my site (not published) can just borrow the blog-post layout for the about page.

So I did this in my `src/layouts/BlogPost.astro`:

```typescript
// …

const {
  title,
  "publication date": pubDate,
  "updated date": updatedDate,
} = Astro.props.frontmatter || Astro.props;

console.log({pubDate})

const pubDateFormatted = pubDate?.toLocaleDateString("en-us", {
  year: "numeric",
  month: "long",
  day: "numeric",
});
```

but I get an error saying that `pubDate?.toLocaleDateString is not a function`. After adding in the `console.log()` call, I see it's a string that looks like a date to me (`"2023-03-08T00:00:00.000Z"`). Normally, I wouldn't expect a string after `zod` gets done with validating the `frontmatter` — I'd expect a proper `Date` object. Here's what the important part of `src/content/config.ts` looks like:

```typescript
const blog = defineCollection({
  schema: z.object({
    title: z.string(),
    description: z.string().optional(),
    "publication date": z
      .string()
      .or(z.date())
      .transform((val) => new Date(val)),
  // …
  }),
});
```

VS Code says that the return type of the arrow function passed to `transform()` is `Date`, and I've been having great results getting nicely-formatted dates on my blog posts. However, once I add ` Astro.props.frontmatter` as a possible place to pull the `publication date` from, I get a full-blown build error instead of just not having titles or publication dates shown on my About page.

Wouldn't it be best if the docs showcased a way that ensures all metadata, whether from a collection's item's front matter or from a standalone page's front matter, gets run through `zod`?

**Comment by sarah11918** [comment] 2023-03-13 12:06
Thanks for this great feedback @adiabatic!

The example from the docs is old and does predate the content collections feature, and I don't believe we tested it against combining content collections with other page props. I think this would make a great addition to our new recipes page, @Jutanium , and this comment gives us a great test case!  :raised_hands:

**Comment by delucis** [comment] 2023-07-27 13:33
Thanks again for this issue — looks like the issue is not really with the props example, but more a request for a new guide to using Zod. This may be out of scope for the Astro Docs for now, so will close.

**Closed by delucis** 2023-07-27 13:33 UTC
Labels: improve documentation, recipe
