### ISSUE TITLE
Document that `compressHTML` doesn't remove all whitespace

### ISSUE THREAD

**Issue by mayank99** [withastro/docs#7502] opened 2024-03-20 13:32 UTC
### Astro Info

```block
Astro:  v4.5.6
Output: static
```

### Describe the Bug

Newlines are left as real whitespace in the HTML output, instead of being removed.

Input
```astro
<p>
 A
 <span>B</span>
 C
</p>
```
results in this output:
```html
<p>
A
<span>B</span>
C
</p>
```
which looks like "A B C" when rendered (instead of "ABC").

The [documentation](https://docs.astro.build/en/reference/configuration-reference/#compresshtml) says:
> By default, Astro removes all whitespace from your HTML, including line breaks, from `.astro` components. This occurs both in development mode and in the final build.

It looks like this behavior might have changed in withastro/astro#7556 / [compiler#816](https://github.com/withastro/compiler/pull/816)?

### What's the expected result?

All whitespace should be collapsed, like the documentation says.

e.g. this should be the output:

```html
<p>A<span>B</span>C</p>
```

If real whitespace is desired, it can always be manually added using `{" "}`. This makes the behavior more predictable.

---

If the current behavior is intentional, then it should be documented correctly.

I can also see valid uses for both scenarios. Maybe there should be a third mode for `compressHTML`? Or an option similar to [`html-minifier`](https://kangax.github.io/html-minifier/)'s "Collapse whitespace" and "Collapse inline tag whitespace"

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zwd8ub?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2024-03-20 14:04
@mayank99 Feel free to create a roadmap discussion https://github.com/withastro/roadmap/discussions with the `compressHTML` idea!

**Comment by mayank99** [comment] 2024-03-20 14:05
Yeah, that makes sense to me. Thanks for the quick response

**Comment by mayank99** [comment] 2024-04-05 03:56
Worth also noting that the prettier plugin will sometimes forcibly insert meaningful whitespace, by breaking up long lines.

(If there was a way to trim whitespace, it wouldn't be an issue)

**Comment by sarah11918** [comment] 2024-05-04 21:43
Thanks for the discussion here!

Would be happy if someone wanted to make a PR to adjust the wording per Erika's note that 

> compressHTML only compresses HTML in lossless manner and that in order to preserve the visual of the authored HTML, it might keep some whitespaces.

The change must be made here (in the main astro repo):
https://github.com/withastro/astro/blob/main/packages/astro/src/%40types/astro.ts#L721

And maybe update the content to something like:

> This is an option to minify your HTML output and reduce the size of your HTML files. Astro removes whitespace from your HTML, including line breaks, from .astro components in a lossless manner. This means that some whitespace may be kept to preserve the visual rendering of your HTML. This occurs both in development mode and in the final build. To disable HTML compression, set the compressHTML flag to false.

**Comment by sarah11918** [comment] 2024-06-15 15:25
Just pinging that we've got a good first issue here we'd still be happy if someone took on! Described what to do in the post above!

**Comment by Dillonpw** [comment] 2024-06-20 13:18
@sarah11918 Id be willing to update this section of the docs later today if no one else has taken it on.

**Comment by sarah11918** [comment] 2024-06-20 14:19
@Dillonpw I don't believe anyone is on it! If you don't see a Docs PR for it, then please do go ahead. Thank you so much! :rocket:

**Comment by sarah11918** [comment] 2024-06-27 16:12
This one was closed by the above PR!

**Closed by sarah11918** 2024-06-27 16:12 UTC
Labels: improve documentation, good first issue, help wanted

**Comment by mayank99** [comment] 2024-06-27 16:31
I feel like the updated documentation is still insufficient and misleading. I mentioned [earlier](https://github.com/withastro/docs/issues/7502#issuecomment-2038838034) that the formatter can forcibly insert whitespace against the author's will. I've been able to work around it is using `prettier-ignore` comments, but it may not be obvious to other users.

**Comment by sarah11918** [comment] 2024-06-28 10:22
OK, so not just "fail to remove" some whitespace, but actually "add unexpected" whitespace? If the comment were updated to include that idea, would that be sufficient?

**Comment by delucis** [comment] 2024-06-28 10:26
If I understand @mayank99 correctly the issue is in two places:

1. If you use a formatter like Prettier, it can add meaningful whitespace to your source files that changes rendering (seems like a bug in https://github.com/withastro/prettier-plugin-astro tbh)

2. After that has happened, `compressHTML` won’t remove/fix that whitespace which the formatter added (which I guess is expected — Astro doesn’t know the extra whitespace was unintentional, so compresses it conservatively)

**Comment by mayank99** [comment] 2024-06-28 13:18
Yeah it's a `prettier-plugin-astro` issue, but I haven't even installed that directly. I believe it comes bundled with the Astro VSCode extension.

I'm not sure what the best way to document this would be, but yeah a brief mention would be nice.
