### ISSUE TITLE
Issue with install dependencies on stackblitz template

### ISSUE THREAD

**Issue by stoddabr** [withastro/docs#4558] opened 2023-09-05 17:27 UTC
### 📝 Issue Description

The stackblitz template on the home page fails to load initially. This is important to fix because this template is a major call-to-action on from the docs homepage.

### 📋 On which page(s) it occurs

The [stackblitz template](https://astro.new/basics?on=stackblitz) linked to on the [home page ](https://docs.astro.build/en/getting-started/)

### 🤔 Expected Behavior

It should run as expected when first loaded

### 👀 Current Behavior

Npm install is failing so the page doesn't load:

```bash
❯ npm install && npm run dev
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@astrojs/prism@3.0.0',
npm WARN EBADENGINE   required: { node: '>=18.14.1' },
npm WARN EBADENGINE   current: { node: 'v16.20.0', npm: '9.4.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@astrojs/telemetry@3.0.1',
npm WARN EBADENGINE   required: { node: '>=18.14.1' },
npm WARN EBADENGINE   current: { node: 'v16.20.0', npm: '9.4.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'astro@3.0.8',
npm WARN EBADENGINE   required: { node: '>=18.14.1', npm: '>=6.14.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.0', npm: '9.4.2' }
npm WARN EBADENGINE }
npm ERR! Failed to fetch dependencies:
npm ERR! - buffer@6.0.3
npm ERR! - string_decoder@1.3.0
npm ERR! - unist-util-generated@2.0.1
npm ERR! - @babel/compat-data@7.22.9
npm ERR! - @types/debug@4.1.8
npm ERR! - sisteransi@1.0.5
npm ERR! - ansi-regex@6.0.1
npm ERR! - is-buffer@2.0.5
npm ERR! - mkdirp-classic@0.5.3
npm ERR! - chokidar@3.5.3
npm ERR! - nlcst-to-string@3.1.1
npm ERR! - picocolors@1.0.0
npm ERR! - space-separated-tokens@2.0.2
npm ERR! - micromark-core-commonmark@1.1.0
npm ERR! - mdast-util-gfm-task-list-item@1.0.2
npm ERR! - kind-of@6.0.3
npm ERR! - debug@4.3.4
npm ERR! - cross-spawn@7.0.3
npm ERR! - lru-cache@5.1.1
npm ERR! - rc@1.2.8
npm ERR! - tar-fs@3.0.4
npm ERR! - browserslist@4.21.10
npm ERR! - @jridgewell/set-array@1.1.2
npm ERR! - ini@1.3.8
npm ERR! - @babel/helper-function-name@7.22.5
npm ERR! - is-unicode-supported@1.3.0
npm ERR! - cli-spinners@2.9.0
npm ERR! - rollup@3.28.1
npm ERR! - reusify@1.0.4
npm ERR! - hast-util-to-parse5@7.1.0
npm ERR! - parse5@6.0.1
npm ERR! - @types/json5@0.0.30
npm ERR! - hast-util-raw@7.2.3
npm ERR! - is-arrayish@0.3.2
npm ERR! - ccount@2.0.1
npm ERR! - vfile-message@3.1.4
npm ERR! - micromark-util-classify-character@1.1.0
npm ERR! - locate-path@6.0.0
npm ERR! - is-binary-path@2.1.0
npm ERR! - napi-build-utils@1.0.2
npm ERR! - ms@2.1.2
npm ERR! - readable-stream@3.6.2
npm ERR! - @types/mdast@3.0.12
npm ERR! - @jridgewell/sourcemap-codec@1.4.15
npm ERR! - rehype-stringify@9.0.4
npm ERR! - cli-boxes@3.0.0
npm ERR! - to-fast-properties@2.0.0
npm ERR! - micromark-util-chunked@1.1.0
npm ERR! - supports-color@5.5.0
npm ERR! - micromark-util-subtokenize@1.1.0
npm ERR! - character-entities@2.0.2
npm ERR! - shiki@0.14.4
npm ERR! - micromark-util-combine-extensions@1.1.0
npm ERR! - rehype-raw@6.1.1
npm ERR! - github-slugger@2.0.0
npm ERR! - has@1.0.3
npm ERR! - readdirp@3.6.0
npm ERR! - update-browserslist-db@1.0.11
npm ERR! - @astrojs/telemetry@3.0.1
npm ERR! - human-signals@5.0.0
npm ERR! - unist-util-is@5.2.1
npm ERR! - pump@3.0.0
npm ERR! - boxen@7.1.1
npm ERR! - js-yaml@4.1.0
npm ERR! - property-information@6.3.0
npm ERR! - @types/babel__core@7.20.1
npm ERR! - comma-separated-tokens@2.0.3
npm ERR! - is-extglob@2.1.1
npm ERR! - wrappy@1.0.2
npm ERR! - streamsearch@1.1.0
npm ERR! - micromark-util-symbol@1.1.0
npm ERR! - color-name@1.1.3
npm ERR! - string-width@6.1.0
npm ERR! - argparse@2.0.1
npm ERR! - vite@4.4.9
npm ERR! - path-key@3.1.1
npm ERR! - mdast-util-definitions@5.1.2
npm ERR! - mdast-util-phrasing@3.0.1
npm ERR! - @esbuild/linux-x64@0.19.2
npm ERR! - unist-util-visit-children@2.0.2
npm ERR! - @nodelib/fs.stat@2.0.5
npm ERR! - esprima@4.0.1
npm ERR! - is-stream@3.0.0
npm ERR! - path-exists@4.0.0
npm ERR! - is-core-module@2.13.0
npm ERR! - stringify-entities@4.0.3
npm ERR! - which-pm@2.1.1
npm ERR! - dequal@2.0.3
npm ERR! - simple-concat@1.0.1
npm ERR! - diff@5.1.0
npm ERR! - is-number@7.0.0
npm ERR! - ieee754@1.2.1
npm ERR! - mimic-response@3.1.0
npm ERR! - character-entities-html4@2.1.0
npm ERR! - ora@7.0.1
npm ERR! - micromatch@4.0.5
npm ERR! - section-matter@1.0.0
npm ERR! - uvu@0.5.6
npm ERR! - end-of-stream@1.4.4
npm ERR! - color-convert@1.9.3
npm ERR! - mdast-util-to-string@3.2.0
npm ERR! - micromark-extension-gfm-footnote@1.1.2
npm ERR! - micromark-factory-label@1.1.0
npm ERR! - unist-util-modify-children@3.1.1
npm ERR! - ansi-styles@3.2.1
npm ERR! - micromark-extension-gfm-autolink-literal@1.0.5
npm ERR! - mdast-util-to-hast@12.3.0
npm ERR! - hast-util-parse-selector@3.1.1
npm ERR! - camelcase@7.0.1
npm ERR! - micromark-util-normalize-identifier@1.1.0
npm ERR! - @babel/helper-simple-access@7.22.5
npm ERR! - micromark-util-decode-numeric-character-reference@1.1.0
npm ERR! - yallist@3.1.1
npm ERR! - micromark@3.2.0
npm ERR! - supports-preserve-symlinks-flag@1.0.0
npm ERR! - queue-tick@1.0.1
npm ERR! - source-map-js@1.0.2
npm ERR! - @babel/helper-module-transforms@7.22.15
npm ERR! - path-to-regexp@6.2.1
npm ERR! - bl@5.1.0
npm ERR! - @webassembly/sharp@0.31.3-blitz.4
npm ERR! - @babel/helper-hoist-variables@7.22.5
npm ERR! - micromark-util-resolve-all@1.1.0
npm ERR! - @babel/core@7.22.15
npm ERR! - caniuse-lite@1.0.30001527
npm ERR! - tsconfig-resolver@3.0.1
npm ERR! - onetime@6.0.0
npm ERR! - shebang-regex@3.0.0
npm ERR! - cookie@0.5.0
npm ERR! - mimic-fn@4.0.0
npm ERR! - micromark-factory-destination@1.1.0
npm ERR! - isexe@2.0.0
npm ERR! - picomatch@2.3.1
npm ERR! - tunnel-agent@0.6.0
npm ERR! - micromark-util-types@1.1.0
npm ERR! - mri@1.2.0
npm ERR! - strip-ansi@7.1.0
npm ERR! - stdin-discarder@0.1.0
npm ERR! - web-namespaces@2.0.1
npm ERR! - clsx@2.0.0
npm ERR! - mdast-util-gfm@2.0.2
npm ERR! - is-docker@3.0.0
npm ERR! - markdown-table@3.0.3
npm ERR! - color@4.2.3
npm ERR! - normalize-path@3.0.0
npm ERR! - log-symbols@5.1.0
npm ERR! - html-escaper@3.0.3
npm ERR! - postcss@8.4.29
npm ERR! - is-extendable@0.1.1
npm ERR! - is-wsl@3.0.0
npm ERR! - @babel/helper-environment-visitor@7.22.5
npm ERR! - @astrojs/markdown-remark@3.0.0
npm ERR! - acorn@8.10.0
npm ERR! - vitefu@0.2.4
npm ERR! - remark-smartypants@2.0.0
npm ERR! - @types/estree@1.0.1
npm ERR! - @types/ms@0.7.31
npm ERR! - micromark-extension-gfm-task-list-item@1.0.5
npm ERR! - which@2.0.2
npm ERR! - type-fest@2.19.0
npm ERR! - gray-matter@4.0.3
npm ERR! - anymatch@3.1.3
npm ERR! - has-flag@3.0.0
npm ERR! - @types/parse5@6.0.3
npm ERR! - @jridgewell/gen-mapping@0.3.3
npm ERR! - hast-util-to-html@8.0.4
npm ERR! - remark-rehype@10.1.0
npm ERR! - github-from-package@0.0.0
npm ERR! - convert-source-map@1.9.0
npm ERR! - graceful-fs@4.2.11
npm ERR! - @astrojs/compiler@2.0.1
npm ERR! - base64-js@1.5.1
npm ERR! - @babel/plugin-transform-react-jsx@7.22.15
npm ERR! - @types/babel__template@7.4.1
npm ERR! - @astrojs/internal-helpers@0.2.0
npm ERR! - color-string@1.9.1
npm ERR! - vfile@5.3.7
npm ERR! - queue-microtask@1.2.3
npm ERR! - server-destroy@1.0.1
npm ERR! - emoji-regex@8.0.0
npm ERR! - prompts@2.4.2
npm ERR! - es-module-lexer@1.3.0
npm ERR! - electron-to-chromium@1.4.508
npm ERR! - is-glob@4.0.3
npm ERR! - sade@1.8.1
npm ERR! - braces@3.0.2
npm ERR! - widest-line@4.0.1
npm ERR! - b4a@1.6.4
npm ERR! - @babel/helper-module-imports@7.22.15
npm ERR! - decompress-response@6.0.0
npm ERR! - kleur@4.1.5
npm ERR! - mdast-util-gfm-footnote@1.0.2
npm ERR! - emoji-regex@10.2.1
npm ERR! - minimist@1.2.8
npm ERR! - preferred-pm@3.1.2
npm ERR! - mdast-util-to-markdown@1.5.0
npm ERR! - jsonc-parser@3.2.0
npm ERR! - shebang-command@2.0.0
npm ERR! - ci-info@3.8.0
npm ERR! - inherits@2.0.4
npm ERR! - micromark-factory-space@1.1.0
npm ERR! - jsesc@2.5.2
npm ERR! - mdast-util-gfm-strikethrough@1.0.3
npm ERR! - chownr@1.1.4
npm ERR! - is-fullwidth-code-point@3.0.0
npm ERR! - retext@8.1.0
npm ERR! - once@1.4.0
npm ERR! - js-tokens@4.0.0
npm ERR! - npm-run-path@5.1.0
npm ERR! - strip-bom@4.0.0
npm ERR! - strip-json-comments@2.0.1
npm ERR! - mime@3.0.0
npm ERR! - simple-get@4.0.1
npm ERR! - @babel/helpers@7.22.15
npm ERR! - unist-util-visit-parents@5.1.3
npm ERR! - merge-stream@2.0.0
npm ERR! - http-cache-semantics@4.1.1
npm ERR! - mdast-util-find-and-replace@2.2.2
npm ERR! - @babel/generator@7.22.15
npm ERR! - micromark-factory-title@1.1.0
npm ERR! - node-addon-api@6.1.0
npm ERR! - util-deprecate@1.0.2
npm ERR! - import-meta-resolve@3.0.0
npm ERR! - fastq@1.15.0
npm ERR! - unist-util-stringify-position@3.0.3
npm ERR! - p-limit@2.3.0
npm ERR! - path-key@4.0.0
npm ERR! - unified@10.1.2
npm ERR! - fs-constants@1.0.0
npm ERR! - glob-parent@5.1.2
npm ERR! - hast-util-whitespace@2.0.1
npm ERR! - @babel/helper-string-parser@7.22.5
npm ERR! - emoji-regex@9.2.2
npm ERR! - strip-ansi@6.0.1
npm ERR! - yallist@4.0.0
npm ERR! - @babel/helper-validator-identifier@7.22.15
npm ERR! - find-up@4.1.0
npm ERR! - color-name@1.1.4
npm ERR! - function-bind@1.1.1
npm ERR! - get-stream@8.0.1
npm ERR! - p-locate@4.1.0
npm ERR! - hast-util-from-parse5@7.1.2
npm ERR! - extend@3.0.2
npm ERR! - @babel/helper-split-export-declaration@7.22.6
npm ERR! - extend-shallow@2.0.1
npm ERR! - kleur@3.0.3
npm ERR! - p-limit@3.1.0
npm ERR! - @jridgewell/trace-mapping@0.3.19
npm ERR! - find-up@5.0.0
npm ERR! - bl@4.1.0
npm ERR! - yargs-parser@21.1.1
npm ERR! - fast-glob@3.3.1
npm ERR! - fast-fifo@1.3.2
npm ERR! - yocto-queue@0.1.0
npm ERR! - p-try@2.2.0
npm ERR! - mimic-fn@2.1.0
npm ERR! - decode-named-character-reference@1.0.2
npm ERR! - argparse@1.0.10
npm ERR! - @esbuild/linux-x64@0.18.20
npm ERR! - micromark-extension-gfm-table@1.0.7
npm ERR! - locate-path@5.0.0
npm ERR! - globals@11.12.0
npm ERR! - lru-cache@6.0.0
npm ERR! - escape-string-regexp@5.0.0
npm ERR! - prebuild-install@7.1.1
npm ERR! - hastscript@7.2.0
npm ERR! - signal-exit@3.0.7
npm ERR! - @babel/types@7.22.15
npm ERR! - fill-range@7.0.1
npm ERR! - expand-template@2.0.3
npm ERR! - @babel/template@7.22.15
npm ERR! - eastasianwidth@0.2.0
npm ERR! - which-pm@2.0.0
npm ERR! - find-yarn-workspace-root2@1.2.16
npm ERR! - @babel/traverse@7.22.15
npm ERR! - execa@8.0.1
npm ERR! - chalk@5.3.0
npm ERR! - @babel/helper-compilation-targets@7.22.15
npm ERR! - buffer@5.7.1
npm ERR! - string-width@5.1.2
npm ERR! - retext-stringify@3.1.0
npm ERR! - unist-util-visit@4.1.2
npm ERR! - unherit@3.0.1
npm ERR! - onetime@5.1.2
npm ERR! - type-fest@0.13.1
npm ERR! - remark-gfm@3.0.1
npm ERR! - @types/babel__generator@7.6.4
npm ERR! - micromark-util-html-tag-name@1.2.0
npm ERR! - micromark-extension-gfm@2.0.3
npm ERR! - micromark-util-encode@1.1.0
npm ERR! - esbuild-wasm@0.18.20
npm ERR! - mdast-util-from-markdown@1.3.1
npm ERR! - @babel/parser@7.22.15
npm ERR! - wrap-ansi@8.1.0
npm ERR! - binary-extensions@2.2.0
npm ERR! - micromark-extension-gfm-tagfilter@1.0.2
npm ERR! - busboy@1.6.0
npm ERR! - nanoid@3.3.6
npm ERR! - strip-bom-string@1.0.0
npm ERR! - prismjs@1.29.0
npm ERR! - streamx@2.15.1
npm ERR! - strip-final-newline@3.0.0
npm ERR! - vscode-textmate@8.0.0
npm ERR! - estree-walker@3.0.3
npm ERR! - run-parallel@1.2.0
npm ERR! - mdast-util-gfm-autolink-literal@1.0.3
npm ERR! - @ampproject/remapping@2.2.1
npm ERR! - is-interactive@2.0.0
npm ERR! - load-yaml-file@0.2.0
npm ERR! - string-width@4.2.3
npm ERR! - @types/resolve@1.20.2
npm ERR! - character-entities-legacy@3.0.0
npm ERR! - which-pm-runs@1.1.0
npm ERR! - retext-smartypants@5.2.0
npm ERR! - chalk@2.4.2
npm ERR! - cli-cursor@4.0.0
npm ERR! - ansi-sequence-parser@1.1.1
npm ERR! - micromark-util-sanitize-uri@1.2.0
npm ERR! - simple-swizzle@0.2.2
npm ERR! - @babel/helper-annotate-as-pure@7.22.5
npm ERR! - micromark-factory-whitespace@1.1.0
npm ERR! - is-plain-obj@4.1.0
npm ERR! - resolve@1.22.4
npm ERR! - longest-streak@3.1.0
npm ERR! - vfile-location@4.1.0
npm ERR! - pkg-dir@4.2.0
npm ERR! - common-ancestor-path@1.0.1
npm ERR! - magic-string@0.30.3
npm ERR! - @types/babel__traverse@7.20.1
npm ERR! - @nodelib/fs.walk@1.2.8
npm ERR! - deep-extend@0.6.0
npm ERR! - rehype@12.0.1
npm ERR! - @babel/plugin-syntax-jsx@7.22.5
npm ERR! - html-void-elements@2.0.1
npm ERR! - escape-string-regexp@1.0.5
npm ERR! - trim-lines@3.0.1
npm ERR! - pify@4.0.1
npm ERR! - vscode-oniguruma@1.7.0
npm ERR! - @astrojs/prism@3.0.0
npm ERR! - trough@2.1.0
npm ERR! - micromark-util-character@1.2.0
npm ERR! - dlv@1.1.3
npm ERR! - to-regex-range@5.0.1
npm ERR! - rehype-parse@8.0.5
npm ERR! - undici@5.23.0
npm ERR! - merge2@1.4.1
npm ERR! - @types/nlcst@1.0.1
npm ERR! - tar-stream@3.1.6
npm ERR! - json5@2.2.3
npm ERR! - @nodelib/fs.scandir@2.1.5
npm ERR! - retext-latin@3.1.0
npm ERR! - escalade@3.1.1
npm ERR! - sprintf-js@1.0.3
npm ERR! - safe-buffer@5.2.1
npm ERR! - node-abi@3.47.0
npm ERR! - @jridgewell/resolve-uri@3.1.1
npm ERR! - path-parse@1.0.7
npm ERR! - p-locate@5.0.0
npm ERR! - @babel/highlight@7.22.13
npm ERR! - restore-cursor@4.0.0
npm ERR! - @types/hast@2.3.5
npm ERR! - detect-libc@2.0.2
npm ERR! - esbuild-wasm@0.19.2
npm ERR! - micromark-util-decode-string@1.1.0
npm ERR! - @babel/helper-validator-option@7.22.15
npm ERR! - bail@2.0.2
npm ERR! - astro@3.0.8
npm ERR! - strip-bom@3.0.0
npm ERR! - micromark-extension-gfm-strikethrough@1.0.7
npm ERR! - semver@7.5.4
npm ERR! - color-convert@2.0.1
npm ERR! - js-yaml@3.14.1
npm ERR! - tar-stream@2.2.0
npm ERR! - ansi-regex@5.0.1
npm ERR! - tar-fs@2.1.1
npm ERR! - ansi-styles@6.2.1
npm ERR! - dset@3.1.2
npm ERR! - parse-latin@5.0.1
npm ERR! - @babel/code-frame@7.22.13
npm ERR! - semver@6.3.1
npm ERR! - @types/unist@2.0.8
npm ERR! - p-limit@4.0.0
npm ERR! - signal-exit@4.1.0
npm ERR! - devalue@4.3.2
npm ERR! - remark-parse@10.0.2

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-09-05T17_20_59_311Z-debug-0.log
```

### 🖥️ Browser

Chrome

### 📄 Additional Information

Running `npm update` before the auto `npm install && npm run dev` commands fixed the issue

**Comment by sarah11918** [comment] 2023-09-17 13:31
Hi @stoddabr ! Thank you for letting us know, but this is not an issue with the documentation site. The Stackblitz link is currently working in most browsers from our recent community tests, but we had recently had reports that the starter template is not working for some users in the Edge browser.

So I'm closing this because it is not a docs issue: docs is displaying the correct link. If you are still having trouble with Stackblitz, please file a GitHub issue on the `withastro/astro` repo so they treat it as a core bug, and/or please do share in our Discord because we very recently confirmed that people were not having issues when using Chrome!

**Closed by sarah11918** 2023-09-17 13:31 UTC
Labels: bug, not for this repo
