### ISSUE TITLE
Improving the docs about @astrojs/tailwind

### ISSUE THREAD

**Issue by ttmc** [withastro/docs#2886] opened 2023-03-19 15:13 UTC
I found it easy to add the Tailwind integration following the docs page at https://docs.astro.build/en/guides/integrations-guide/tailwind/

After doing that, adding Tailwind utility classes to my HTML seemed to work as expected.

But now I have some questions about the final CSS that gets generated when I do `astro build`:

1. Does the generated CSS include only the CSS I actually used in my site?
2. Is the CSS minified, and if so, by what? Can that be configured and if so, how?

Based on looking at the generated CSS from a build, I believe the answers are:

1. Yes, once you add Astro's Tailwind integration, Tailwind always generates only the CSS you *actually* use in your site, as per https://tailwindcss.com/docs/optimizing-for-production . There is nothing extra you have to do to turn that on.
2. Yes, the CSS is minified, but I don't know what did it, or how to turn it off.

I don't know if those answers are correct. *Correct* information about all of the above should be in the docs page about Astro's Tailwind integration.

**Comment by ElianCodes** [comment] 2023-03-19 16:53
Hey there!

1. So, the Tailwind integration added via `astro add`, will automatically set the `content` in the generated `tailwind.config.cjs` with all possible Astro extensions and integrations. This tells the Tailwind compiler (which uses JIT by default) to purge all not used utility classes that don't appear in those files.

2. The CSS is minified by Tailwind itself, I don't think that Astro interferes with this. (Not totally sure about this). Of course, you can also modify this behaviour with [PostCSS](<https://tailwindcss.com/docs/using-with-preprocessors#using-post-css-as-your-preprocessor>).

In my opinion, this is all expected behaviour & I don't think this differs from the Tailwind docs itself, therefore (IMO) not needed to document. But if people seem to struggle with this, I'm open to changes, curious to see what rest of people think.

**Comment by sarah11918** [comment] 2023-03-20 14:12
So, one challenge we face in docs is that it's not practical for us to document how *other* things work... because we have to maintain that, and we don't always have a good way of knowing when another service has updated on *their* end.

We do try to stick to documenting *usage* of the thing *in Astro*, and of course, in highlighting anything that might be confusing or unexpected with the interaction of the two.

So I would tend to document, for example, only things that:
- work differently *in Astro* than they otherwise would
- require extra configuration *in your Astro project* to get things to work together
- affect *other parts* of your Astro project (e.g. if installing X means that now Y works a little differently)
... basically what we have control over, or require because you're using a thing *in* Astro.

We do include links to other docs in relevant sections. So if there are things inherent and totally expected in Tailwind but that we specifically think Astro users might struggle with or be confused by, we could look for places where we can link to relevant Tailwind documentation to send them to the correct Tailwind info.

I also recognize that Tailwind is I think our most-installed integration? So it could be worth "relaxing our rule" a bit if we know that so many people are going to be using the Tailwind integration and if we can pre-empt a lot of support requests. But again, one reason to link to Tailwind docs is because they should be considered the canonical source for Tailwind usage, and should be responsible for supporting Tailwind users in general.

**Comment by sarah11918** [comment] 2023-05-02 03:57
Closing this as I don't ultimately think it's something for our documentation.

**Closed by sarah11918** 2023-05-02 03:57 UTC
Labels: improve documentation
