### ISSUE TITLE
Error accessing env with import.meta.env

### ISSUE THREAD

**Issue by ukpagrace** [withastro/docs#9750] opened 2024-10-19 22:02 UTC
### 📝 Issue Description

Loading an env with import.meta.env does not work, but when i used process.env it does.

### 📋 On which page(s) it occurs

https://docs.astro.build/en/guides/environment-variables/

### 🤔 Expected Behavior

I expect the command to load an env to work and not return an error indicating the env is undefined 

### 👀 Current Behavior

Instead it is not working, following the instruction i get an env that is undefined.

### 🖥️ Browser

chrome

**Comment by ArmandPhilippot** [comment] 2024-10-20 14:42
Hi @ukpagrace! Thanks for taking the time to report your issue. I'm afraid we need a little more information to help you:
* Is this a specific section on this page?
* Can you provide more details about the error? How does it occur?

I have set up [a minimal project](https://stackblitz.com/edit/astro-import-meta-env?file=.env,src%2Fpages%2Findex.astro&on=stackblitz) but I am unable to reproduce the error... As you can see, the variables are loaded and displayed in the console. So the documentation  about using `import.meta.env` doesn't seem wrong to me...

**Comment by sarah11918** [comment] 2024-10-22 12:04
Hi @ukpagrace ! This repo is for reporting errors with our documentation that need fixing, and  as Armand mentioned, I don't believe there is an issue with the documentation as it shows the recommended, expected use of Astro. 

You may have something in your setup that is not working as expected, or there may be a bug in Astro that is causing the documentation not to work, but this repository can't help you with either of those things, unfortunately!  

I will also note that the documentation regarding environment variables may depend on whether you are using the latest stable version of astro, the beta v5 version (which has its own set of documentation) or the `astro:env` feature (which is experimental in v4 but no longer experimental in v5).

For support with your project, we recommend visiting our Discord where people will be more than happy to help you troubleshoot your own code! https://astro.build/chat If you believe this is a bug in Astro, you can file an issue on the Astro repo and include a minimal reproduction so that others can evaluate. If this is an Astro bug, then our process is to fix the bug, not change the documentation! Our documentation always displays the intended behaviour of Astro, and if that doesn't actually work, then that helps us know when things are bugs that need to be fixed!

So I will close this as it is not an issue for docs, but you are welcome to file an issue at https://github.com/withastro/astro if you can provide a reproduction of the bug, and to visit our friendly Discord to ask community members for help with your project!

**Closed by sarah11918** 2024-10-22 12:04 UTC
Labels: bug
