### ISSUE TITLE
Base path not working like the docs said

### ISSUE THREAD

**Issue by harrytran998** [withastro/docs#2140] opened 2022-12-02 02:12 UTC
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

NodeJs 18 LTS + SSR nodejs standalone

### What package manager are you using?

yarn 3

### What operating system are you using?

Mac

### Describe the Bug

https://docs.astro.build/en/reference/configuration-reference/#base

The docs said it only affects production. But seem in development, this still have effect.

When I config `astro.config.js` like this

```js
import { defineConfig } from 'astro/config';
import svelte from '@astrojs/svelte';
import AstroNode from '@astrojs/node';

export default defineConfig({
  output: 'server',
  integrations: [svelte()],
  base: '/ok',
  server: {
    port: 4000,
    host: '0.0.0.0',
  },
  adapter: AstroNode({
    mode: 'standalone',
  }),
});

```
In dev mode, it will throw a warning like this

```bash
[serve]  404   /favicon.ico
[dev] Requests for items in your public folder must also include your base. /favicon.svg should be /ok/favicon.svg. Omitting the base will break in production.
```

And the screen shows like this

```
404: Not found
In your site you have your base path set to [/ok/](http://localhost:3000/ok/). Do you want to go there instead?
```

In my mind, I think this base path is like the concept of NextJs. But seem not correct like they do.

--- With NextJs concept
When I config `basePath` to `/ok` --> In production mode, at least this will auto append `/ok` to the href with `next/link`. And the assets must be appended with base path `ok/`.

But seem Astro not auto append href 🤔.

### Link to Minimal Reproducible Example

Stackblitz did not work correctly with the base path. So your team needs to pull this source code 😆.

https://github.com/harrytran998/rep-astro-base-path
(Here is the version of stackblitz to check https://stackblitz.com/edit/github-ncwvvs?file=astro.config.mjs)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sarah11918** [comment] 2022-12-29 13:11
I think this is related to the rabbit hole of PRs that started here: #1643 that I am trying to pin down! I suspect we actually *have* proper docs that were blocked by some unexpected behaviour. I think we're unblocked, and I'm trying to confirm whether we can now re-merge a previous docs fix that we intended to have!  :sweat_smile:

**Comment by sarah11918** [comment] 2022-12-29 14:29
And, looks like I should be able to close this! Although this previous PR to our configuration reference was merged, it was reverted to fix a bug with the intention we'd add it back after bug fix. Bug is fixed, and we'll be re-introducing this into docs:  https://github.com/withastro/astro/pull/4954/files

If you notice any problems, feel free to reopen!

**Closed by sarah11918** 2022-12-29 14:29 UTC

**Comment by sarah11918** [comment] 2022-12-29 15:00
Followup: https://github.com/withastro/astro/pull/5693 has been made to address this. Comments can be made there!
