### ISSUE TITLE
Github Codespace: cannot preview astro website 

### ISSUE THREAD

**Issue by TusharShahi** [withastro/docs#3484] opened 2023-06-07 11:09 UTC
### What version of `astro` are you using?

2.0.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

Github Codespaces is returning 502 Bad Gateway for any astro template written on astro 2. It seems to work fine for projects build on astro 1.

Here are a few theme templates from official Astro website which did not work for me:

1. https://astro.build/themes/details/astro-paper/
2. https://astro.build/themes/details/modern-personal/

<img width="694" alt="Screenshot 2023-06-07 at 4 39 27 PM" src="https://github.com/withastro/astro/assets/28409475/ae8e440e-c8dc-4939-8fd0-05d40579a395">

### Link to Minimal Reproducible Example

https://tusharshahi-fuzzy-dollop-r7vq55j5rx9hpj47-3000.preview.app.github.dev/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by CommanderGL** [comment] 2023-06-15 22:41
I think that it would be better for them to just find a way to patch this (don't no why it does this.)

**Comment by sarah11918** [comment] 2023-06-22 13:45
Hi @TusharShahi , @CommanderGL ! Are either of you able to confirm that this is still a problem? I'm not sure this is ours to document, especially if it is a bug or something that should just be fixed. It might even be an issue to take up with GitHub/Codespaces?

But, it's at least something for our support squad on Discord to be made aware of so they can give advice as necessary. I'll close this issue here, as I don't think it's really something for us to document, and track when it starts working again. But even if closed you can reply here, or better yet, head into our Discord and either make a support thread where we do track issues that people are having, and we have people there who will explore further for you... (and then come back to us in docs, if it's truly a last resort and we expect this to be a long-lasting issue that we would consider documenting).

**Comment by donvito** [comment] 2023-08-04 11:21
still doesn't work with codespaces

**Comment by delucis** [comment] 2023-08-05 21:03
Can confirm I ran into this the other day while testing https://github.com/withastro/starlight/pull/434.

For some reason GitHub Codespaces require you to run `astro dev` or `astro preview` with the `--host` flag in order to avoid the 502 error. Maybe we add a small note to our [“In-browser editor” docs](https://docs.astro.build/en/editor-setup/#in-browser-editors)?

**Comment by ElianCodes** [comment] 2023-08-07 21:18
@delucis, tbh, this is very strange to me 🤔 but +1 to add it to the docs. Even if it's a temp issue

**Comment by sarah11918** [comment] 2023-08-09 21:04
Thanks for confirming, @donvito! Would you like to PR a change to our docs, as @delucis described?

We could also probably update that 2nd bullet point to read "GitHub Codespaces" (since this page was originally written before Codespaces existed?  :sweat_smile: )  (I'm not sure how many people would choose github.dev over Codespaces now. We could include both?)

I can confirm this is NOT necessary on Gitpod nor Stackblitz, so it's probably just a Codespaces thing. In that case, maybe we switch the order and put Codespaces *below* Gitpod so that a comment can apply just to that one, and not break the flow of the other bullet points?

**Comment by jacobthesheep** [comment] 2023-09-21 06:42
Is this still an on-going issue?

**Comment by sarah11918** [comment] 2023-11-09 01:12
Closing this for inactivity, and we haven't heard issues of this lately!

**Closed by sarah11918** 2023-11-09 01:12 UTC
Labels: improve documentation, good first issue, help wanted
