### ISSUE TITLE
Documenting workarounds for define:vars and classes

### ISSUE THREAD

**Issue by lostra01** [withastro/docs#1017] opened 2022-07-16 17:15 UTC
# Introduction

Welcome everyone reading this.
Please feel free to weigh in on any of the following topics, with any suggestions or questions you have. The more we talk about it the more we can find a solution that benefits the most.

Some of the features mentioned here can be missing documentation, can be a missing feature, or something that will be coming in an update later, as well as workarounds and troubleshooting.

## Styles with `define:vars`

Using `define:vars` in style and script tags can cause known issues in both cases when components are re-used in the same layout/page, although they appear very differently. The common ground being that workarounds need to be used to get them working properly. It is mentioned in an [RFC here.](https://github.com/withastro/rfcs/blob/main/proposals/0008-style-script-behavior.md)

The questions for this section - which probably the core team will be able to answer:
- Is this functionality working as expected and will not be changed in the forseeable future?
- If they work as expected, do we need to document them as a main feature?
- If they are not a main feature, should they be documented as troubleshooting/workaround?

### Current behavior 

When using `define:vars` in a style tag, during runtime, a tag is inserted into the page, that defines a `--foo` variable, which can then be accessed via `var(--foo)`. If the users are trying to re-use the same component with a variable that's ought to be dynamic, the previous `--foo` will be overwritten. Essentially re-using a component will turn each of these variables into the last injected component.

**Example:**
Let's create a simple component, that has a fixed size, and takes the background color from a variable, that is defined in the page:
```astro
---
import ColoredTile from './ColoredTile.astro';
---

<div class="grid">
    <ColoredTile backgroundColor="teal" />
    <ColoredTile backgroundColor="red" />
    <ColoredTile backgroundColor="olive" />
</div>
```
The component simply passes the variable to the style tag from `Astro.props`. Users could expect three different colored tiles in their grid, but they will end up with a color for each that's defined by the very last element, in our case **olive**. The component should simply look like this:
```astro
---
const {backgroundColor} = Astro.props;
---
<div class="grid-element"></div>

<style define:vars={{backgroundColor}}>
    .grid-element{
        width: 100px;
        height: 100px;
        background-color: var(--backgroundColor);
    }
</style>
```

Since `--backgroundColor` keeps getting overwritten, the first two tiles will get the `olive` value as well instead of their original values. 

### Workaround #1:

When using a single property that needs to change dynamically when re-using the same component, the easiest and most straightforward thing to do is to pass the value into the `style=` attribute of the HTML Tag. For example, if we change our component from the previous `define:vars` method to the one below, the background colors are working as expected:
```astro
---
const {backgroundColor} = Astro.props;
---
<div class="grid-element" style=`background-color:${backgroundColor}`></div>

<style>
    .grid-element{
        width: 100px;
        height: 100px;
    }
</style>
```
### Workaround #2:

When working with multiple rules, adding them to the style attribute can result in long, ugly and unreadable strings, like:
`style=background-color:${backgroundColor};color:${fontColor};font-size:${fontSize};text-align:${textAlign}`
It is hard to maintain and not easy on the eyes. It is easier and more straightforward to create a string literal variable with the values in it. In our component it would look like:
```astro
---
const {backgroundColor, fontColor, fontSize, textAlign} = Astro.props;
const tileStyle = `
    background-color: ${backgroundColor};
    color: ${fontColor};
    font-size: ${fontSize};
    text-align: ${textAlign};
`;
---
<div class="grid-element" style={titleStyle}></div>

<style>
    .grid-element{
        width: 100px;
        height: 100px;
    }
</style>
```

### Downsides / Caveat:

One of the biggest downsides of the methods above is that the styles are inlined into the HTML Tag. This comes with all the downsides of in-lining, such as no re-usability, no media queries for different screen sizes, etc. The style - since it is inline - is no longer scoped to the component, it is just injected into the code as-is.

Another solution is to - if possible - prepare multiple classes, and pass those class names for your components.

This actually brings us to the second issue.
## Passing `class` to Astro Components

An issue was already raised about this topic by #995 . After some discussion with @sarah11918 I'd like to keep this section here as well, because there's no certainty that this should be in the documentation, and if yes, in what section. 

For fresh users, thinking along the lines of `<MyComp class="someClass" />` is something that could be expected to work as-is, but it's not the case. 

The main problem is that the component can consist of a single HTML Tag, it can have multiple nested tags, or consist of multiple (_component-wise_) root tags. It's not easy to decide if using the `class` attribute on the component should add it to the root tag, all the tags, or all the root tags. It is essentially left for the user to pass the class names to the correct tags.

This brings another slight issue. Since `class` is a reserved word in JavaScript, trying to use it as `const {class} = Astro.props` will result in an error. The user has to use a different name for the variable, eg. `className`.

### Workaround

Thanks to JSX it is possible to have the best of both worlds and use `<MyComp class="someClass" />` in a page or layout. All the users have to do is use the rename feature of JSX to change `class` into any other name they desire. A quick example of such a component:
```astro
---
const {class: className} = Astro.props;
---

<div class={className}></div>
```
While this is actually a JavaScript and not entirely an Astro issue, it is still undocumented and been asked a few times in the support threads. This issue can also be iterated on to provide more functionality to the code above. An Astro-specific `class:list` can be used to pass in an array of several possible value types. This feature IS documented inside the [common directives](https://docs.astro.build/en/reference/directives-reference/#classlist). But if a workaround/troubleshooting post is made for the issue above, direct linking to this section would be beneficial.

Another user, @mayank99 has made an amazing comment about passing various properties and attributes to a custom component. In their code snippet the whole `Astro.props` is spread into the targeted HTML Tag. This is another code/feature that could be documented either as workarounds, or advanced usage.
```astro
---
export type Props = { [k: string]: unknown };
---
<div {...Astro.props} />
```

## `define:vars` and Scripts

When using `define:vars` with scripts, the same issue _would_ happen as it does with the styles, but JavaScript actually stops us a step before that. 
When users type `<script define:vars={{foo}}>` what happens is that Astro turns that define into a `let foo` inside the script. The issue with this, is when using multiple components and trying to pass different variables to Script, we will be greeted with a re-declaration error. 
Going around the issue here, is not as simple as it is with styles. If someone uses `define:vars` on a script tag, the script is automatically inlined, and the dreaded `redeclaration of let foo` appears.

```astro
---
const {foo} = Astro.props;
---

<div></div>
<script define:vars={{foo}}>
</script>
```

There are two ways to go around this behavior. One is using an external package, such as `astro-xelement` which lets you handle scripts and variables better. It comes with a few extra things to do, so it might not always be the best option.

If there's no complex code, and some variable just has to be passed to the script tag, the easiest method is to use a custom data attribute. This can then be accessed inside the script easily, without a redeclaration error.

```astro
---
const {foo} = Astro.props;
---

<div></div>
<script data-foo={foo}>
    console.log(document.currentScript.dataset.foo); // Prints the correct value once per component
</script>
```

## Final Thougts

The main question of this issue is the ones outlined in the beginning. 

- Is this functionality working as expected and will not be changed in the forseeable future?
- If they work as expected, do we need to document them as a main feature?
- If they are not a main feature, should they be documented as troubleshooting/workaround?

@sarah11918 @delucis @natemoo-re @matthewp @aFuzzyBear

**Comment by mayank99** [comment] 2022-07-16 17:39
I agree with those questions. If it's working as expected, then it's super confusing and should be documented. @bholmesdev ran into this exact issue on stream when trying to randomize a CSS variable for each instance of a component.

I believe the most elegant workaround (for "Styles with define:vars") is to use inline CSS variables. 
```diff
---
const {backgroundColor} = Astro.props;
---
- <div class="grid-element"></div>
+ <div class="grid-element" style={`--backgroundColor:${backgroundColor}`}></div>

- <style define:vars={{backgroundColor}}>
+ <style>
    .grid-element{
        background-color: var(--backgroundColor);
    }
</style>
```

As for "Passing class to Astro Components", I do not see that as part of this issue. It's just JavaScript.

**Comment by lostra01** [comment] 2022-07-16 17:49
That's a really amazing option you got there! I did not think of defining the variable inline!

**Comment by natemoo-re** [comment] 2022-07-16 18:16
@lostra01 thanks for this incredibly detailed write up!

> Is this functionality working as expected and will not be changed in the forseeable future?

I don't consider any of the current behavior to be working as intended.

Revisiting this feature _was_ not on our radar to do before the 1.0.0 release but it honestly seems like this got lost in the shuffle. This post makes a very good case that `define:vars` needs to be fixed ASAP!

Given how visible and frustrating it is currently, I'd love to explore a few options. Let's avoid documenting workarounds on the assumption that this can be fixed in the next week or so. If that can't happen, I'll be sure to circle back with a long-term plan for this feature.

**Comment by lostra01** [comment] 2022-07-16 19:40
Thank you for the input @natemoo-re ! This issue shall be put to sleep then, and when it gets fixed, we can focus on a proper documentation.

**Comment by delucis** [comment] 2022-08-03 14:23
Thanks so much for all this work documenting here — I guess we’re all happy it’s no longer needed 😅 

I’ll close this now that `define:vars` behaves as expected. Thanks again @lostra01!

**Closed by delucis** 2022-08-03 14:23 UTC
Labels: On hold
