### ISSUE TITLE
The scroll bar will move to the top every time the sidebar is clicked

### ISSUE THREAD

**Issue by tyj-321** [withastro/docs#8998] opened 2024-08-02 11:37 UTC
### 📝 Issue Description

in the sidebar, when I click on a lower menu, the scroll bar will move to the top, so I need to scroll down again

![PixPin_2024-08-02_19-32-36](https://github.com/user-attachments/assets/5175b3eb-329d-48f3-a3a7-f08ddbc2b18a)

### 📋 On which page(s) it occurs

https://docs.astro.build/en/guides/styling/
and other lower menus

### 🤔 Expected Behavior

when I click the menu, the scroll bar will not move to the top

### 👀 Current Behavior

when I click the menu, the scroll bar will move to the top

### 🖥️ Browser

chrome 127.0.6533.72

**Comment by sarah11918** [comment] 2024-08-05 18:35
Hi @tyj-321 ! This is normal behaviour for multi-page sites, unfortunately!  :smile:  You can see it in other docs sites that are not JavaScript apps, too.

It's not a bug, though we have been discussing whether this is something we can and should change in Starlight. There are some annoying edge cases to figure out, and we were surprised it's *really* not as easy to ensure that this is good behaviour for everyone in all the different ways people are using their sidebars (collapsed or not, scrolled or not, on a page that doesn't even *have* a sidebar entry or not...)

So I'm going to close this because it's not a bug! We're just deciding on the behaviour we want. You can view the [open draft PR](https://github.com/withastro/starlight/pull/2150) we've been working on (and finding out just how difficult it is to find a sensible solution) and participate in the [Starlight Discussion](https://github.com/withastro/starlight/discussions/971) there!

**Closed by sarah11918** 2024-08-05 18:35 UTC

**Comment by tyj-321** [comment] 2024-08-06 01:27
> Hi @tyj-321 ! This is normal behaviour for multi-page sites, unfortunately! 😄 You can see it in other docs sites that are not JavaScript apps, too.
> 
> It's not a bug, though we have been discussing whether this is something we can and should change in Starlight. There are some annoying edge cases to figure out, and we were surprised it's _really_ not as easy to ensure that this is good behaviour for everyone in all the different ways people are using their sidebars (collapsed or not, scrolled or not, on a page that doesn't even _have_ a sidebar entry or not...)
> 
> So I'm going to close this because it's not a bug! We're just deciding on the behaviour we want. You can view the [open draft PR](https://github.com/withastro/starlight/pull/2150) we've been working on (and finding out just how difficult it is to find a sensible solution) and participate in the [Starlight Discussion](https://github.com/withastro/starlight/discussions/971) there!

I understand. Thank you for your patient answer ❤
