### ISSUE TITLE
[Cloudflare Adapter] auto generated `_routes.json` can easily exclude Functions invocation routes limits

### ISSUE THREAD

**Issue by twodft** [withastro/docs#3039] opened 2023-04-13 07:33 UTC
> By default, @astrojs/cloudflare will generate a _routes.json file that lists all files from your dist/ folder and redirects from the _redirects file in the exclude array. This will enable Cloudflare to serve files and process static redirects without a function invocation. Creating a custom _routes.json will override this automatic optimization and, if not configured manually, cause function invocations that will count against the request limits of your Cloudflare plan.

We should add a note to [Cloudflare adapter](https://docs.astro.build/en/guides/integrations-guide/cloudflare/#custom-_routesjson) document since the default auto-generated `_route.json` file can easily exclude the limits and cause Cloudflare Pages deployment failed.

A example error log 
```
Error: Failed to publish your Function. Got error: Error 8000057: Rules in `_routes.json` are over the 100 rule limit. Refer to https://cfl.re/3FsE4aF.
```

The limits on [Cloudflare Pages Functions doc](https://developers.cloudflare.com/pages/platform/functions/routing/#limits)

> Functions invocation routes have the following limits:
> 
> You must have at least one include rule.
> You may have no more than 100 include/exclude rules combined.
> Each rule may have no more than 100 characters.

**Comment by delucis** [comment] 2023-04-13 09:43
This sounds like a bug to me! Would you be able to share a reproduction in the main Astro repo?

https://github.com/withastro/astro/issues/new/choose

**Comment by twodft** [comment] 2023-04-24 03:50
> This sounds like a bug to me! Would you be able to share a reproduction in the main Astro repo?
> 
> https://github.com/withastro/astro/issues/new/choose

Sorry, forget to mention that I've set `export const prerender = true` for my `src/blog/[...slug].astro` to pretender all my blog posts, this caused all my blog posts listed inside the `_route.json`'s exclude list and then exclude the limits of the route and finally cause the Cloudflare Pages deployment failed.

So we may need to add some notice in the doc, like this in [Svelte's doc about Cloudflare adapter](https://kit.svelte.dev/docs/adapter-cloudflare#options)
> You can have up to 100 include and exclude rules combined. Generally you can omit the routes options, but if (for example) your <prerendered> paths exceed that limit, you may find it helpful to manually create an exclude list that includes '/articles/*' instead of the auto-generated ['/articles/foo', '/articles/bar', '/articles/baz', ...].

**Comment by sarah11918** [comment] 2023-05-02 03:31
If this is a Cloudflare limitation that is true in Astro the way it is in the Svelte documentation you linked, then it sounds like this could be a good addition to the docs. Would you be willing to make a PR to the Cloudflare page with the relevant notice, @twodft  ?

**Comment by delucis** [comment] 2023-05-02 08:49
I still think this is an Astro bug if anything. Yes, it’s a Cloudflare limitation, but because we generate `_routes.json` for users, we’d basically be saying “Don’t have more than 100 routes”. We could provide logging and maybe redesign the adapter to bundle routes better?

I’m not sure needing to document “Don’t have more than 100 pages” is a great path either. (SvelteKit is a bit different because as an SPA you likely rarely have 100 routes, whereas with prerendering in Astro, you can easily hit this with 100 Markdown pages.)

**Comment by delucis** [comment] 2023-05-02 09:33
Just chatted with some of the team and we’re tracking this here: https://github.com/withastro/astro/issues/6516

I think the goal will be to handle this better without needing to update documentation, so going to close this issue. Thanks again for drawing our attention to it @twodft!

**Closed by delucis** 2023-05-02 09:33 UTC
Labels: good first issue, add new content, help wanted
