### ISSUE TITLE
Content Collections page still tells people to upgrade to Astro v2.0!

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#4869] opened 2023-09-29 17:58 UTC
### 📚 Subject area/topic

content collections

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/content-collections/#migrating-from-file-based-routing

### 📋 General description or bullet points (if proposing new content)

The guide for converting a site to content collections is outdated, and says you should update to version 2.0! This, and the link, should both be updated to say 3.0!

The only changes needed should be to update both the text and the link from "2" to "3"!

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

none

**Comment by AdamVacha** [comment] 2023-09-30 02:11
Upon inspecting the page it appears to me the issue is already resolved? If not I'd be glad to do so.

**Comment by Suraj-kumar00** [comment] 2023-10-05 01:36
Hi @sarah11918 , How are you doing?
Can I work on this issue? Can you please assign it to me?

**Comment by silent1mezzo** [comment] 2023-10-14 04:20
This is done right?

**Comment by TheOtterlord** [comment] 2023-10-14 10:02
Yep! Looks like this issue wasn't linked to close on merge. Thanks for the bump!

**Closed by TheOtterlord** 2023-10-14 10:02 UTC
Labels: improve documentation, good first issue, help wanted
