### ISSUE TITLE
Astro Discord invite link not working.

### ISSUE THREAD

**Issue by tanishqkrk** [withastro/docs#4672] opened 2023-09-12 20:11 UTC
### 📝 Issue Description

The Discord invite on the right sidebar in Astro docs is probably expired, or corrupt. I had to join the server via search on Discord.
Please take a look.
I'd add a new link but I think it would expire within a few days, so I'm not making a PR for it.

![image](https://github.com/withastro/docs/assets/90266615/8cf03369-d9a3-444e-baca-3ff185be7615)

### 📋 On which page(s) it occurs

https://astro.build/

### 🤔 Expected Behavior

The link should be working, I assume it's expired or corrupted.

### 👀 Current Behavior

Link isn't working

### 🖥️ Browser

Brave 1.57.62

**Comment by jacobthesheep** [comment] 2023-09-12 23:42
It works for me. Not sure what could cause that.

**Comment by ElianCodes** [comment] 2023-09-13 10:02
hey @tanishqkrk! Does https://astro.build/chat work for you?

**Comment by tanishqkrk** [comment] 2023-09-14 01:32
Nope, tried Chrome, Firefox and Brave. Two different Discord accounts. The same issue persists.

**Comment by Ranily57** [comment] 2023-09-14 13:27
It's not a Astro bug, but a discord one, the link work for me too. 

2 issue: 

- Discord is bugged on your computer
- You get banned from this server (i don't think)

**Comment by sarah11918** [comment] 2023-09-17 13:11
I'm not sure what could be causing this, but the link does appear to be functioning for several people who have tested this. I am glad you found our Discord server and that you reported it! 🙌  But I will have to close this issue as non-reproducible.

**Closed by sarah11918** 2023-09-17 13:11 UTC
Labels: bug
